apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: a10ippools.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                subnet: 
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NoController
                used:
                  type: string
                  description: Used address list
      additionalPrinterColumns:
      - name: Name
        type: string
        description: Specify the IP pool name
        jsonPath: .spec.name
      - name: Subnet
        type: string
        description: Specify the Subnet 
        jsonPath: .spec.subnet
      - name: Status
        type: string
        jsonPath: .status.state
  names:
    kind: A10IPPool
    plural: a10ippools
    singular: a10ippool
    shortNames:
    - a10ippool
  scope: Cluster
