apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: activeactivehadevices.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                ip-address:
                  type: string
                secret:
                  type: string
                  description: "Specify the secret with respect to the thunder device"
                partition:
                  type: string
                  description: "Specify the thunder partition to be used"
                  default: "shared"
                status:
                  type: string
                  default: "NoController"
                axapiTimeout:
                  type: integer
                  description: "Specify a time limit for aXAPI requests"
                  minimum: 1
                  maximum: 60
                  default: 3
                axapiRetries:
                  type: integer
                  description: "Specify the max retries when connection failed to ACOS"
                  minimum: 0
                  maximum: 10
                  default: 2
                axapiRetryBackoffTime:
                  type: integer
                  description: "Specify backoff time for aXAPI retry when ACOS is not ready or connection lost"
                  minimum: 0
                  maximum: 60
                  default: 0
              required:
                - name
                - ip-address
                - secret
      additionalPrinterColumns:
      - name: Name
        type: string
        description: Specify the thunder name
        jsonPath: .spec.name
      - name: IP-Address 
        type: string
        description: Specify IP Address of the thunder
        jsonPath: .spec.ip-address
      - name: Secret
        type: string
        description: Specify Secret of the thunder
        jsonPath: .spec.secret
      - name: Partition
        type: string
        description: Specify partition of the thunder
        jsonPath: .spec.partition
      - name: Status
        type: string
        jsonPath: .spec.status    
  names:
    kind: ActiveActiveHADevice
    plural: activeactivehadevices
    singular: activeactivehadevice
    shortNames:
    - a10activehadevice
  scope: Namespaced
