apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: serverssls.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Server SSL Template Name
                ca-certs:
                  type: array
                  items:
                    type: object
                    properties:
                        ca-cert:
                          type: string
                          description: Specify CA certificate secret name
                        ca-cert-partition-shared :
                          type: integer
                          default: 0
                        server-ocsp-srvr:
                          type: string
                          description: Specify authentication server
                        server-ocsp-sg:
                          type: string
                          description: Specify service-group (Service group name)
                server-name:
                  type: string
                  description : Specify Server Name,

                crl-certs:
                  type: array
                  items:
                    type: object
                    properties:
                        crl:
                          type: string
                          description: Certificate Revocation Lists (Certificate Revocation Lists file name) secret name
                        crl-partition-shared:
                          type: integer
                          default: 0
                          description: Certificate Revocation Lists Partition Shared
                cipher-without-prio-list:
                  type: array
                  items:
                    type: object
                    properties:
                        cipher-wo-prio:
                            type: string
                            enum:
                            - SSL3_RSA_DES_192_CBC3_SHA
                            - SSL3_RSA_RC4_128_MD5
                            - SSL3_RSA_RC4_128_SHA
                            - TLS1_RSA_AES_128_SHA
                            - TLS1_RSA_AES_256_SHA
                            - TLS1_RSA_AES_128_SHA256
                            - TLS1_RSA_AES_256_SHA256
                            - TLS1_DHE_RSA_AES_128_GCM_SHA256
                            - TLS1_DHE_RSA_AES_128_SHA
                            - TLS1_DHE_RSA_AES_128_SHA256
                            - TLS1_DHE_RSA_AES_256_GCM_SHA384
                            - TLS1_DHE_RSA_AES_256_SHA
                            - TLS1_DHE_RSA_AES_256_SHA256
                            - TLS1_ECDHE_ECDSA_AES_128_GCM_SHA256
                            - TLS1_ECDHE_ECDSA_AES_128_SHA
                            - TLS1_ECDHE_ECDSA_AES_128_SHA256
                            - TLS1_ECDHE_ECDSA_AES_256_GCM_SHA384
                            - TLS1_ECDHE_ECDSA_AES_256_SHA
                            - TLS1_ECDHE_RSA_AES_128_GCM_SHA256
                            - TLS1_ECDHE_RSA_AES_128_SHA
                            - TLS1_ECDHE_RSA_AES_128_SHA256
                            - TLS1_ECDHE_RSA_AES_256_GCM_SHA384
                            - TLS1_ECDHE_RSA_AES_256_SHA
                            - TLS1_RSA_AES_128_GCM_SHA256
                            - TLS1_RSA_AES_256_GCM_SHA384
                            - TLS1_ECDHE_RSA_AES_256_SHA384
                            - TLS1_ECDHE_ECDSA_AES_256_SHA384
                            - TLS1_ECDHE_RSA_CHACHA20_POLY1305_SHA256
                            - TLS1_ECDHE_ECDSA_CHACHA20_POLY1305_SHA256
                            - TLS1_DHE_RSA_CHACHA20_POLY1305_SHA256
                dh-type:
                  type: string
                  enum:
                  - 1024
                  - 1024-dsa
                  - 2048
                ec-list:
                  type: array
                  items:
                    type: object
                  properties:
                    ec:
                      type: string
                      enum:
                      - secp256r1
                      - secp384r1
                close-notify:
                  type: integer
                  default: 0
                version:
                  type: integer
                  minimum: 30
                  maximum: 34
                  default: 33
                dgversion:
                  type: integer
                  minimum: 30
                  maximum: 34
                  default: 31
                server-certificate-error:
                  type: array
                  items:
                    type: object
                    properties:
                      error-type:
                        type: string
                        enum:
                        - email
                        - ignore
                        - logging
                        - trap
                oscp-stapling:
                  type: integer
                use-client-sni:
                  type: integer
                  default: 0
                renegotiation-disable:
                  type: integer
                  default: 0
                session-cache-size:
                  type: integer
                  minimum: 0
                  maximum: 128
                  default: 0
                session-cache-timeout:
                  type: integer
                  minimum: 1
                  maximum: 7200
                cipher-template:
                  type: string
                certificate:
                  type: object
                  properties:
                    cert:
                      type: string
                      description: Certificate secret name
                    key:
                      type: string
                      description: Client private-key  secret name (Key Name)
                    passphrase:
                      type: string
                      description: Password Phrase
            status:
              type: object
              properties:
                state:
                  type: string

      additionalPrinterColumns:
      - name: Template Name
        type: string
        description: Server SSL template
        jsonPath: .spec.name
      - name: Status
        type: string
        jsonPath: .status.state

  scope: Namespaced
  names:
    plural: serverssls
    singular: serverssl
    kind: ServerSsl

