apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templatevirtualports.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Template SLB Server Name"
                conn-limit:
                  type: integer
                  minimum: 1
                  maximum: 64000000
                  default: 64000000
                  description: "Connection limit"
                conn-rate-limit:
                  type: integer
                  minimum: 1
                  maximum: 1048575
                  description: "Connection rate limit"
                user-tag:
                  type: string
                  description: "User Tag" 
              required:
                - name         
            status:
              type: object
              properties:
                state:
                  type: string
      additionalPrinterColumns:
      - name: Name
        type: string
        jsonPath: .spec.name 
      - name: Status
        type: string
        jsonPath: .status.state  
  names:
    kind: TemplateVirtualPort
    plural: templatevirtualports
    singular: templatevirtualport
    shortNames:
    - a10tvp
  scope: Namespaced
