apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templatetcpproxies.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Template Tcp Proxy Name"
                backendWscale:
                  type: integer
                  minimum: 1
                  maximum: 14
                  description: "The TCP window scale used for the server side"
                idleTimeout:
                  type: integer
                  minimum: 1
                  maximum: 2097120
                  default: 600
                  description: "Idle Timeout in interval of 60 seconds"
                halfCloseIdleTimeout:
                  type: integer
                  minimum: 60
                  maximum: 120
                  description: "TCP Half Close Idle Timeout in seconds"
                retransmitRetries:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 5
                  description: "Number of Retries for retransmit"
                synRetries:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 5
                  description: "SYN Retry Numbers" 
                finTimeout:
                  description: "FIN timeout (sec), default is disabled (number)"
                  type: integer
                  minimum: 1
                  maximum: 60
                resetFwd:
                  description: "Send reset to server if error happens"
                  type: boolean
                resetRev:
                  description: "Send reset to client if error happens"
                  type: boolean
              required:
                - name         
            status:
              type: object
              properties:
                state:
                  type: string
      additionalPrinterColumns:
      - name: Name
        type: string
        jsonPath: .spec.name 
      - name: Status
        type: string
        jsonPath: .status.state  
  names:
    kind: TemplateTcpProxy
    plural: templatetcpproxies
    singular: templatetcpproxy
    shortNames:
    - a10ttp
  scope: Namespaced