apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualservers.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                ip-address:
                  type: string
            
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NoController
      additionalPrinterColumns:
      - name: Name
        type: string
        description: Specify the virtual-server name
        jsonPath: .spec.name
      - name: VIP 
        type: string
        description: Specify the IP Address for the virtual-server
        jsonPath: .spec.ip-address
      - name: Status
        type: string
        jsonPath: .status.state
  names:
    kind: VirtualServer
    plural: virtualservers
    singular: virtualserver
    shortNames:
    - a10vip
  scope: Namespaced
