apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualservers.tkc.a10networks.com
spec:
  group: tkc.a10networks.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                ip-address:
                  type: string
                ip-pool:
                  type: string
                  description: Specify the Calico IPPool name (since TKC v2.0)
                a10-ip-pool:
                  type: string
                  description: Specify the A10 IPPool name (Since TKC v2.4)
                acl-id:
                  type: integer
                  description: Specify the Access list ID
                vrid:
                  description: "Join a vrrp group (Specify ha VRRP-A vrid)"
                  type: integer
                  minimum: 1
                  maximum: 31
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NoController
      additionalPrinterColumns:
      - name: Name
        type: string
        description: Specify the virtual-server name
        jsonPath: .spec.name
      - name: VIP 
        type: string
        description: Specify the IP Address for the virtual-server
        jsonPath: .spec.ip-address
      - name: IPAM
        type: string
        description: Specify the IPAM IP Pool name
        jsonPath: .spec.ip-pool
      - name: Status
        type: string
        jsonPath: .status.state
    - name: v1alpha1
      served: true
      storage: false
      deprecated: true
      deprecationWarning: tkc.a10networks.com/v1alpha1 VirtualServer deprecated.Please consider migrate to tkc.a10networks.com/v1 VirtualServer
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                ip-address:
                  type: string
                ip-pool:
                  type: string
                  description: Specify the Calico IPPool name (since TKC v2.0)
                a10-ip-pool:
                  type: string
                  description: Specify the A10 IPPool name (Since TKC v2.4)
                acl-id:
                  type: integer
                  description: Specify the Access list ID
                vrid:
                  description: "Join a vrrp group (Specify ha VRRP-A vrid)"
                  type: integer
                  minimum: 1
                  maximum: 31
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NoController
      additionalPrinterColumns:
      - name: Name
        type: string
        description: Specify the virtual-server name
        jsonPath: .spec.name
      - name: VIP 
        type: string
        description: Specify the IP Address for the virtual-server
        jsonPath: .spec.ip-address
      - name: IPAM
        type: string
        description: Specify the IPAM IP Pool name
        jsonPath: .spec.ip-pool
      - name: Status
        type: string
        jsonPath: .status.state    
  names:
    kind: VirtualServer
    plural: virtualservers
    singular: virtualserver
    shortNames:
    - a10vip
  scope: Namespaced
