apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualservers.slb.tkc.a10networks.com
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  #annotations:
  # "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: slb.tkc.a10networks.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                ip-address:
                  type: string
            
            status:
              type: object
              properties:
                state:
                  type: string
                  default: no controller
      additionalPrinterColumns:
      - name: Name
        type: string
        description: Virtual Server Name
        jsonPath: .spec.name
      - name: VIP 
        type: string
        description: The number of jobs launched by the CronJob
        jsonPath: .spec.ip-address
      - name: Status
        type: string
        jsonPath: .status.state
  names:
    kind: VirtualServer
    plural: virtualservers
    singular: virtualserver
    shortNames:
    - a10slbvs
  scope: Namespaced
